### ISSUE TITLE
Who is maintainer of this package?

### ISSUE THREAD

**Issue by dfdx** [JuliaGPU/CLBLAS.jl#17]
I believe it's time to bring this package to the next level, providing high-level API, documentation and all other signs of maturity. I've already started some changes and plan to make much more, but I don't want to break old APIs and go against old ideas without agreement with maintainers / original authors of this package. So I wonder who should I address for decision regarding important changes? 

cc: @ekobir @jakebolewski 

If nobody is currently responsible for this package, I'd like to take over it (including bugs and improvements).

**Comment by jakebolewski** [comment]
I think you can assume "ownership" of the package.  I don't do OpenCL/GPU programming anymore so I'm not going to be the best maintainer going forward.  The idea of using Github groups is that collaborators are sophisticated enough to do PR's and improvements on their own and that there is no one "owner".

**Comment by dfdx** [comment]
Well, the reason I ask is that very often maintainers or "owners" have a general vision for project development, while "ordinary" contributors see only distinct parts (note quotes, since it all is rather arbitrary). But since nobody has an active plan for this package, I assume it's safe to move it in a direction which I believe is the most appropriate. 

Thanks for comments.
