### ISSUE TITLE
Unable to build in OS X

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGPU/CLBLAS.jl#33]
I have `brew install clblas` but get the following error.  The build instruction link https://github.com/clMathLibraries/clBLAS/wiki/Build is also broken.

```julia
julia> Pkg.build("CLBLAS")
INFO: Building CLBLAS
===============================[ ERROR: CLBLAS ]================================

LoadError:     OSX not oficially supported.
    Find manual build instructions on: https://github.com/clMathLibraries/clBLAS/wiki/Build

while loading /Users/solver/.julia/v0.6/CLBLAS/deps/build.jl, in expression starting on line 38
```

**Comment by SimonDanisch** [comment]
Can you try out: https://github.com/JuliaGPU/CLBLAS.jl/pull/34 ?

**Comment by dlfivefifty** [comment]
Didn't work:
```julia
julia> Pkg.build("CLBLAS")
INFO: Building Homebrew
INFO: Building CLBLAS
Error: No available formula with the name "clblas" 
Error: No available formula with the name "clblas" 
```

**Comment by dlfivefifty** [comment]
You might need `homebrew/science/clblas`

**Comment by SimonDanisch** [comment]
I see... yeah i dont have osx to try this out... Did it work after changing that?

**Comment by dfdx** [comment]
I've just tried `homebrew/science/clblas` on MacBook and `Pkg.build` worked for me. `Pkg.test`, however, throws a number of errors, but I've never configured this computer for any GPU work, so it's better if someone else checks it (I'll be able to setup OpenCL on Mac only in 2 weeks or so).

**Comment by SimonDanisch** [comment]
Well, Apple is really not the best for GPU work...
Please open an issue with an error log, maybe someone else has OSX and can look into it! :)

**Comment by dlfivefifty** [comment]
I've made a pull request for `homebrew/science/clblas`:

https://github.com/JuliaGPU/CLBLAS.jl/pull/35

**Comment by dlfivefifty** [comment]
This works for me now.
